<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container89KzPmG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container89KzPmG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container89KzPmG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container89KzPmG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container89KzPmG\App_KernelDevDebugContainer([
    'container.build_hash' => '89KzPmG',
    'container.build_id' => '9456b92e',
    'container.build_time' => 1700478945,
], __DIR__.\DIRECTORY_SEPARATOR.'Container89KzPmG');
